### ISSUE TITLE
Default Text for Input does not display labelProp

### ISSUE THREAD

**Issue by rposener** [rniemeyer/knockout-jqAutocomplete#10]
On Initialization, the labelProp is not shown when binding to an array of Objects.  This provides an odd behavior.  I have this fiddle to demonstrate: http://jsfiddle.net/rposener/z0gbokb2/3/  - the Expected text in the input should be "Year 2000" when binding initialization is done, as that is what is shown when that value is selected.

**Comment by rposener** [comment]
I have submitted a pull request for further discussion / review about how to fix this.

**Comment by rniemeyer** [comment]
@rposener - thanks. I was just starting to look at the changes needed and they were basically what you have. Will add a couple of comments on the PR.

**Comment by rniemeyer** [comment]
Thanks this one has been merged.
