### ISSUE TITLE
invalid module name jquery.ui

### ISSUE THREAD

**Issue by jkokorian** [rniemeyer/knockout-jqAutocomplete#13]
I think the requirejs define should be rewritten as:
define(["knockout", "jquery", "jquery-ui/autocomplete"], factory);

I think the standard AMD module name for jqueryUI is jquery-ui, and the components are separated files in a folder. This would also be in accordance with your 'knockout-sortable' project.

**Comment by rniemeyer** [comment]
Fixed. Thanks!

**Comment by jkokorian** [comment]
Glad I could contribute, keep up the good work!
