### ISSUE TITLE
Using plugin from Knockout custom component

### ISSUE THREAD

**Issue by berlaga** [rniemeyer/knockout-jqAutocomplete#25]
Hi,
I'm trying to use plugin from inside Knockout custom component.

Template component-auto-complete.html

`<div id="widget" class="form-group">
    <label for="tags">Select person</label>
    <input style="margin-bottom:5px;"
           placeholder="3 letters minimum to search"
           class="form-control"
           id="tags"
           data-bind="jqAuto: { value: myValue(), source: getOptions, inputProp: 'FullName', valueProp: 'Id', labelProp: 'FullName', options: { minLength: 3, delay: 800} }" />
    <span style="margin-top:5px;" data-bind="text: 'Person\'s id: ' + myValue(), visible: myValue()"></span>
</div>`

Model component-auto-complete.js

`
define(['knockout', 'jquery'], function (ko, $) {

    function AutoCompleteWidgetViewModel(params) {
        this.myValue = ko.observable();
 
    }

    AutoCompleteWidgetViewModel.prototype.getOptions = function (searchTerm, callback) {
        $.ajax({
            dataType: "json",
            url: params.serviceUrl,
            data: {
                query: searchTerm
            },
            beforeSend: function (xhr) {
                $("#tags").val("Loading data..");
            }
        })
        .done(callback)
        .always(function () {
            $("#tags").val(searchTerm);
        });

    };
    return AutoCompleteWidgetViewModel;
});
`

Component is loaded using Require JS loader.
`
     require.config({
            paths: {
                'jquery': '/scripts/jquery-1.9.1',
                'knockout': '/scripts/knockout-3.4.0',
                'text': '/scripts/text',
                'jquery-ui/autocomplete': '/scripts/jquery-ui-1.11.4',
                'autocomplete-plugin': 'scripts/knockout-jqAutocomplete'
            }
                
        });

       require(["knockout", "jquery", "jquery-ui/autocomplete", "text", 'autocomplete-plugin'], function () { });
`

Component registration

`            ko.components.register('super-auto-complete', {
                viewModel: { require: 'app/components/auto-complete-widget/component-auto-complete' },
                template: { require: 'text!app/components/auto-complete-widget/component-auto-complete.html' }
            });
`

Component usage

`                    <div data-bind='component: { name: "super-auto-complete", params: { serviceUrl: serviceLocation } }'></div>`

Now, problem is plugin is not working. I have a suspicion it's because component is loaded using AMD. 

Any help?

**Comment by rniemeyer** [comment]
@berlaga - Not quite sure, but I would be happy to help investigate. Is it possible for you to send me a sample that I can run either zipped up or pushed up to GH?  rniemeyer at gmail dot com

**Comment by berlaga** [comment]
Hi Ryan,

Thanks for getting back to me. Attached is VS solution. Should work in VS
2013 and 2015. It's a bit messy, I used it to play with Knockout JS
components and AMD loading.
The idea was to integrate auto complete plugin as a Knockout component, so
I can reuse it later.

Look at default1.aspx. This is my attempt to do the encapsulation.

https://drive.google.com/folderview?id=0B5cQV9MQUlS5bDgwamVXck1SbFk&usp=sharing


Thanks in advance,
Alex

**Comment by rniemeyer** [comment]
@berlaga - I figured out what is going on here.  The jqAuto binding is getting attached to the Knockout instance loaded via require.js.  Your start-up code is using the Knockout that is loaded from the script tag (placed on window.ko). So, there are two instances of KO in play.

You would want to remove your Knockout script reference and move your start up code into the callback from your main require statement. Using the "ko" instance that would be coming in as the first argument.

It looks like perhaps you have some additional code issues with your usage of autocomplete, but this should allow you to troubleshoot those errors now. Thanks!

**Comment by berlaga** [comment]
Hi Ryan,

Is till can't make it work. May you can put together an example? After all
using require js for AMD loading is a recommended way from Knockout web
site.

Thanks,
Alex

**Comment by rniemeyer** [comment]
@berlaga - I can try to take a closer look at your component code tomorrow. To get past the AMD issue, here are the steps to take in your code:

1- Comment out or delete the script tag that references `knockout` directly that is towards the top of default1.aspx
2- Take the code that creates your component and applies bindings and move it from being in its own script tag to being in the callback for your `require` call.  So, it would be like:

```
require(["knockout", "jquery", "jquery-ui/autocomplete", "text", 'autocomplete-plugin'], function(ko) {

            function AssembleServiceUrl(api) {
                return window.location.protocol + "//" + window.location.host + "/" + api;
            }


            ko.components.register('super-auto-complete', {
                viewModel: { require: 'app/components/auto-complete-widget/component-auto-complete' },
                template: { require: 'text!app/components/auto-complete-widget/component-auto-complete.html' }
            });

            function myViewModal() {
                var self = this;

                self.serviceLocation = AssembleServiceUrl("api/people");

                self.value = "125";

                self.serachValue = ko.observable();
            }

            ko.applyBindings(new myViewModal());
});
```

**Comment by berlaga** [comment]
Ryan, thank a lot. It works now :)  Make sense too..

**Comment by berlaga** [comment]
Here is a full example code on Plunker 
https://plnkr.co/WJTLlyHIkWe0nBPctuqr
