### ISSUE TITLE
zIndex is not a function

### ISSUE THREAD

**Issue by BillStrait** [rniemeyer/knockout-jqAutocomplete#30]
I believe this error started when updating to the latest build of jQuery/jQuery-UI. I've attempted to simplify the page as much as possible using example code to verify the problem is not on my end.

html:

    <head>

    <script src="/Scripts/jquery-3.1.1.js"></script>

    <script src="/Scripts/jquery-ui-1.12.1.js"></script>

    </head>

    <body>
   
    <input data-bind="jqAuto: { value: myValue, source: myOptions}" />

    <script src="/Scripts/knockout-3.4.1.js"></script>

    <script src="/Scripts/knockout-jqueryui.min.js"></script>

    <script src="/Scripts/knockout-jqAutocomplete.js"></script>

    <script src="/Scripts/jqatest.js"></script>

    </body>

jqatest.js:

    var vm = function (){

        var self = this;

        self.myValue = ko.observable();

        self.myOptions = ["one", "two", "three"];

    }
    ko.applyBindings(vm);`

error:
`Uncaught TypeError: Unable to process binding "jqAuto: function (){return { value:myValue,source:myOptions,inputProp:'name',labelProp:'description',valueProp:'id'} }"
Message: this.element.zIndex is not a function` it hits at knockout-3.4.1.js:72. The knockout-jqAutocomplete.js line that throws is 79.

**Comment by BillStrait** [comment]
I'm an idiot who forgot to check if autocomplete works without this plugin. It does not. Problem is on my end.

**Comment by rniemeyer** [comment]
@BillStrait Thanks for following up!
